### ISSUE TITLE
change webadmin port to 80/443

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/f5-cloudserviceeaplab#4]
the dns_webadmin which is part of the demo uses port 10000, 
some corporate block outside traffic to anything that's not 80/443 so they can't complete the demo 
please change the port and the documentation to 80/443 
thanks !

**Comment by yoctoalex** [comment]
Hello,

The port has been changed to 80 and later will be changed to 443.
10000 is still working but will be deprecated and closed.

Thank you for the feedback!
