### ISSUE TITLE
change not reflected in the demo 

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/f5-cloudserviceeaplab#5]
after step - https://github.com/f5devcentral/f5-cloudserviceeaplab#6-update-monitoring-to-blocking-via-ui 
EAP is in blocking, but sending another illegal file type request from POSTMAN still goes through to the server 

POSTMAN is adding the Connection: Kepp-alive header by default and maintains the TCP connection for a long time. this results in the subsequent request still hitting the 'old' policy. this can be confusing and may lead to wasted troubleshooting time. 

editing the POSTMAN requests that are creating the attacks to include a 'Connection: close' header fixes the issue.

**Comment by yoctoalex** [comment]
Thank you! 'Connection: close' has been included to the attack requests.
